project:
  type: website
  output-dir: docs

website:
  title: "Parul V. Patil"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Publications"
        href: publications.qmd
      - software.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: Patil_Parul_CV.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

