---
title: "Curriculum Vitae"
---

## Education

- **Ph.D. Statistics**, Department of Statistics, Virginia Tech, May 2026 (Anticipated)

    Advisors: Dr. Robert B. Gramacy, Dr. Leah R. Johnson.
    
    Research Interests: Bayesian Statistics, Gaussian Processes, Model Calibration, Surrogate Modelling, Forecasting.

- **M.Sc. Statistics**
Department of Statistics, University of Mumbai, India, Oct 2020

- **B.Sc. Statistics**
Ramnarain Ruia Autonomous College, Mumbai, India, May 2018

## Experience
- Statistical Collaborator, Statistical Applications and Innovations Group, Virginia Tech 
    
    Assisted 15+ clients from industry and academia with designing their       experiments, performing analysis, creating useful visuals, and provided     guidance in methods that can be used to answer their research              questions. Conducted weekly walk-in sessions to guide clients with         their analyses and approve methodologies, and troubleshoot or debug        code as necessary. Developed, reviewed, taught, and piloted short          courses such as Linear Regression, Mixed Models and Bootstrapping in R.

- Graduate Teaching Assistant, Virginia Tech
    
    Assisted with grading assignments for 50-100 students enrolled in          graduate and undergraduate courses such as Biological Statistics,          Engineering Statistics, Design of Experiments as well as a course in       Computational Modelling and Data Analysis. Held office hours to help       students with the course, provided guidance and cleared concepts one on     one.

- Quality Control Intern, Xpress Minds Edutainment Pvt. Ltd., India
 
    Applied Six Sigma techniques to minimize the time spent while              optimizing the number of registrations and increased the total number      of registrations from 700,000 to 1 million. Performed weekly quality       and hygiene audits to ensure productivity of 20+ business development      executives were up to the mark. Forecasted the expected daily number of     registrations for the upcoming month based on historical daily data        from the past year.

## Presentations

- Workshop: "Gaussian Process Modeling for Time Dependent Data"
    - VectorByte training workshop at Notre Dame in June 2025.
    - Ecological Forecasting Initiative Conference workshop at Virginia Tech, Blacksburg n June 2025. 
    - VectorByte training workshop at Virginia Tech Research Centre, Washington D.C in July 2024.
- Poster: "Gaussian Process Forecasting for Tick Population Dynamics"
    - Presented at Ecological Forecasting Initiative (EFI) Conference at Virginia Tech, Blacksburg in May 2025.
    - Kernel Methods in Uncertainty Quantification and Experimental Design (IMSI workshop) at University of Chicago in March 2025.
    - Presented at Corporate Partners at Virginia Tech in November 2024.
    - Presented at International Society of Bayesian Analysis World Meeting (ISBA) at Ca’ Foscari University, Venice,
Italy in July 2024.
    - Presented at Women in Data Science (WiDS) Conference at Virginia Tech in February 2024.

## Publications

1. **Patil, P. V.** `bhetGP`: Bayesian Heteroskedastic Gaussian Processes (CRAN package)

2. **Patil, P. V.**, et al. (2025) Vecchia approximated Bayesian heteroskedastic Gaussian processes. (submitted)

3. **Patil, P. V.**, et al. (2025) Gaussian process forecasting for sparse ecological time series. (submitted)

4. Resler ,L. M., **Patil P. V.**, et al. (2024). Patterns of native and invasive lianas of Virginia’s Ridge and Valley forests in relation to land use history (Southeastern Geographer.)
